#!/usr/bin/env bash
set -euo pipefail

OUT="README.md"
EXCLUDE=("common" ".git" "build" ".github")

echo "# DSA + C++ Practice" >"$OUT"
echo "" >>"$OUT"
echo "Auto-generated by generate_readme.sh." >>"$OUT"
echo "" >>"$OUT"

for topic_dir in */; do
	topic="${topic_dir%/}"
	skip=false
	for ex in "${EXCLUDE[@]}"; do
		[[ "$topic" == "$ex" ]] && skip=true
	done
	$skip && continue

	# skip empty topic folders
	if [ -z "$(ls -A "$topic_dir" 2>/dev/null)" ]; then
		continue
	fi

	echo "## $topic" >>"$OUT"
	echo "" >>"$OUT"

	for problem_dir in "$topic_dir"*/; do
		[ -d "$problem_dir" ] || continue
		problem="${problem_dir%/}"
		problem="${problem##*/}"
		echo "- $problem" >>"$OUT"
	done
	echo "" >>"$OUT"
done

echo "Generated $OUT"
